/* eslint-disable */
// Generated by Wrangler by running `wrangler types worker-configuration.d.ts --include-runtime=false` (hash: 55cdb333eed6a0010dee2b8f7ddf0a9a)
declare namespace Cloudflare {
	interface Env {
		BLOG_READS: KVNamespace;
		ASSETS: Fetcher;
	}
}
interface Env extends Cloudflare.Env {}
